### ISSUE TITLE
does it support 4.8 ?

### ISSUE THREAD

**Issue by ghost** [rokeller/Lucene.Net.ObjectMapping#6]
does it support lucen.net 4.8 NuGet package?

**Comment by rokeller** [comment]
Yes, the latest [RC of Lucene.Net.ObjectMapping](https://www.nuget.org/packages/Lucene.Net.ObjectMapping/1.1.0-rc3) supports the [latest beta of Lucene.net 4.8](https://www.nuget.org/packages/Lucene.Net/4.8.0-beta00005).
