### ISSUE TITLE
Linq

### ISSUE THREAD

**Issue by sairfan1** [rokeller/Lucene.Net.ObjectMapping#7]
Hi, did you get any luck on applying Linq methods? like code in your examples

`using (Searcher searcher = new IndexSearcher(directory))
{
    IQueryable<BlogPost> posts =
        from post in searcher.AsQueryable<BlogPost>()
        where obj.Tag == "lucene"
        orderby obj.Timestamp descending
        select post;
}`

Also in you examples, its hard to know what name spaces are required.
Thanks

**Comment by rokeller** [comment]
Hi,

I've updated documentation, and also added an [example](https://github.com/rokeller/Lucene.Net.ObjectMapping/tree/example/examples/DirectoryWeb). Please check if that answers your question.

As far as namespaces are concerned, the vast majority of APIs are in common Lucene.net namespaces, that you would use/need anyway. For instance, the extensions for documents (`ToDocument` and `ToObject`) are in the namespace `Lucene.Net.Documents`, which also holds the `Document` object from Lucene.net. That means, normally you won't need any additional namespaces other than the ones you'll use from Lucene.net anyway :)
